language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
install: composer install --dev
env:
  global:
  - secure: IlkPIfz6AgkclwxUa4FT2wwbmTidG60EZ6SlpiC+foL/OOYPm5DdCtFkeLDn/tfRD9sNfxH0z0Jp1JcyPL8/jtTY/DQCOrvXX6PUI0s1HvuPXhockrmDSFTHroZykjyLwsRpN3K7lydlyayizQjwhm55ps+UUgcK4bD7pGpFJ4c8Tt3PiqRBk9Kqk8QRpV8Yb1PMQ7ALp+NFglWEiWsprsxIwfalXTgEf5NQHh9HpgtX6CO03koTjkbNddQoSkJDZy0zkiD7EZYthvWK8yX1fOI4tIcM7l6ujSP2OE3l2f0tAO02Gjx03bbJTjUXlEKQnmpgKdBrXQCwYEgv92F7LhWtuW5gTR+hAWdx3xDh0RDK1dIgHp9vnBpkbaUsvFhuRII52lBODsyv/RFt3EetBXqVvvQ51yvrMYYleHB9lK2g6zWTN4QwcnwODCUIohqyM0BkopfL29JhMRwPBZq4uB2aozN+of6De5ritpgjne7q2/Ffnf1SN90yaHysG8fqg6NWXevyt4xBAFSkdtZPLiBv3W+a7oMfR9tzFmnzL1Uj2R8HD7hXIwbjcS8O3oLfSSRMJJYP8kdjnNknHYAeH2eg5tu4QlmZFLXnDR5ldjwfPwvzmsj0O6xDGi6iwAFJSw2k7vD+P3lUA9pgQZzhwjV4mWFEN6XZEuiiRAKUr+k=
  - secure: vH6rkDn7NN139iADWNsZ2UdSJ4ap1M0JSjD/aAD2eaS9PGB0WmH1Aaqa8o8BuIA7Ex6RqqLWb0uwOP6PZjMEMftRIP0yFN+QgYsEBfd4X4ieIPhJK/4lNReRTbQrzEQgZuHl61zm2coJY7KoHL8CJjWAogznYZoMQtdlkM6LqJyn3t5YmvzzBwVczXujj9T78OKKN1mnYjiU+lYTnt5JaxwoP0M/uPsSxjCYWsAC3xKQuc4h1enI4SG0mafRunDx+Fj/ar/NaY/Gtx6ziYtdTvjw23N0up1ltN1wct9G0qbA01HSDfzFl5DWKdu/WY8CtExUG+AOSEFs17iMDEjnTGvpb6wEDsdZkkwxJ4U9UIRHCJNdEyKZLvX74pHZGmYWM33vE6BPfPGa0+5e2mw8TvfonnfhsCCYEvl39g70tznAPZztwFPcHl12Hkdo+3CNXiR0kbw3LSHYP3kRE3VJktW9dC11DsIFfE1U/92Rb3rKIk1OpHvcgYcmzs+8nR8D+xkmitKulyZP+4jQbtoRomiZLffxzJ72eLKGTjRnXrwSLd4dqvoJbpSH2JTJzRdudNTa6a0JneHDZTbXZRHCJuNJJhqP3CzpXxHmjT/7kbHU+IqgaCpK5V4IWcPTkAT214MoKWNfPy8ItJD4okTPvuQ8k+W0DCrFtk3ku/OM8qg=
