language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly

install: composer install --dev
env:
  global:
  - secure: 1hmRGYm7oumtWk6j9ppK8orbYFTB01t/VKtc7Ir90mx/AGqj52YT8w5cWz3Q3UegmVQN6a+QR9iTUvtAgvrVHrbGCEeyNYeOCgKs0X1m/AYYYT1t9VCUtj+pjykQhVxyb+HT3tCfq73o7fTtJFPBIWpoU5sjdlEyLPtZDry+VnhEQhgP2PF58AoBC1h0DxzTbmTASDIqyzQuMH8z3l/xGy9ifP/j1csQl+V0lzdaEQ1ciaxCC262OUiF4a/Cmgg1z6n71vi458UYq5mMOTqxeG3YVmYbuBTgP1RRxZEE53DE5/F19sHFN65ph2QRUaGkMZrpk9fsFjWNBv10xpQIc2UU7GNzbd+rQHshZkJ3SqI/HboJRL+KUFV/WItRHc7yT31O5ZZSR+F0bRqzxGxlyqEQt1X/daipBuoLG7ZvcpyxQf4gmZVrKul9rsIFrxmg1jcrmt9Q//okETUNY6RmtERvDzwNgTexDsJYYUVPLlAFnJYweBpMqwJ4VkbXkfyxqoEVryBn58KO4put3XBRgAXRarEHVVcUBvm9aWtpSq6LfLzKgfGOeMzm7a6XqZvYQJ/QQAqBrvB2DmP2bZu/THidPXwSmnjcEOi1SKxu/X+dEx53fKlAbhYdmgLOAOQIIzCHKTSCxGyo7vbXA3WkuRfg6aj7uQ/m49lcvH+eM30=
  - secure: IxqJP/UtPyRbdRTmBShL5uCdrntmb9o1yBJqtneHVjYUsfUEOcc3AnGuVqgAgfLBZoxBLgm6h2OsQ07ZhRgqVRukYdVUVaVQ62UHg//7DPjJvQVK7fV5cjlfaOpnxQ1zz+aeSH6TW4rBBv3OMHyCQR897dNv/Zk42ihgj4ToDGWGcgv4JvL/kP7zZpg7Cw6U154E+i0Ln/KM/ugBZEMYoMkR++/GaJfqT1oOzIFzuUh7UM65qt3QT4gRsz8FsPJEMZCBao72Xi8mE8tATFwQuijxQD70d3LhdGBwKuP4kPpWyEMbwWTrAOWAB845uE36gJSQkuH+9UpICebtkoG4cHn6ys5iubgjDx+mmBjb4zP6kJOqZaD6sk6+saLGWcbrAk5z/kPIXhPwfTwNBGyH1yg2Um859IX5fPuLnMJTenMOxaMe1Xhjnz6rvhMy71ncHmxpyJ87yk/kuDTlRAKCQAsyZtp0UjPNkhYX4bk/IwcF0tS7CPTMOfRW810aZIQlsNA1NqumO4amOD063hNUqXR8ZbM/5n4CBQZCCchAE+uTivKsJgUrXiafrPwvhayFli4cWx5Hye3MFhpLRvkczEVXY+ifAPM47NGrBMQjomtcoER1yWpmm+aTkjiZ/KS7InbHFnyCNgIGuQPM/JioL7y6wQQ/9sBZrNNOkYOhgZs=
